name: Build and Release Zolanime

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    env:
      PUB_CACHE: ${{ github.workspace }}\.pub-cache

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update version in pubspec.yaml
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}".TrimStart("v")
          (Get-Content pubspec.yaml) -replace '^version: .*', "version: $ver+$env:GITHUB_RUN_NUMBER" | Set-Content pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
        shell: bash

      # WYMUSZAMY BUDOWANIE WINDOWSA (msix:create sam tego czasem nie robi)
      - name: Build Windows App
        run: flutter build windows --release

      # Budowanie instalatora MSIX
      - name: Build MSIX Package
        run: dart run msix:create --install-certificate false

      - name: Rename MSIX
        run: mv build/windows/x64/runner/Release/*.msix Zolanime-Windows-Installer.msix

      # Budowanie APK na Androida
      - name: Build Android App
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk Zolanime-Android-Installer.apk

      # Publikacja wygenerowanych plików ze zaktualizowanymi nazwami
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            Zolanime-Windows-Installer.msix
            Zolanime-Android-Installer.apk
          token: ${{ secrets.GITHUB_TOKEN }}
