name: Build and Release Zolanime

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Desktop Support
        run: flutter config --enable-windows-desktop

      # Budowanie instalatora MSIX dla Windowsa
      - name: Build MSIX Package
        run: dart run msix:create --install-certificate false

      - name: Rename MSIX
        run: mv build/windows/x64/runner/Release/zolanime.msix Zolanime-Windows-Installer.msix

      # Budowanie APK na Androida
      - name: Build Android App
        run: flutter build apk --release

      - name: Rename APK
        run: mv build\app\outputs\flutter-apk\app-release.apk Zolanime-Android-Installer.apk

      # Publikacja MSIX i APK do GitHub Releases
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            build/windows/x64/runner/Release/*.msix
            Zolanime-Android.apk
          token: ${{ secrets.GITHUB_TOKEN }}
